Rails views
Yuliya-Kirich/thinknetika_base pull request #12
Opened 2022-10-21 00:48 UTC by Yuliya-Kirich

1. implemented all standard actions and views for resource question. 
2. added footer, which displays the current year, author's name, project name. 
3. added a helper for the title of the page for creating and editing a question. 
added date helper in footer. 
added helper with links to author and project.

2022-10-21 09:50 UTC, VidgarVii requested changes

2022-10-21 09:50 UTC, VidgarVii commented on Gemfile
> +#gem 'pagy'
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file

2022-10-21 09:50 UTC, VidgarVii commented on Gemfile
> +#gem 'pagy'
этим гемом не будем пользоваться. Лучше его удалить полностью, а не прятать за комментом

2022-10-21 09:50 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @questions = @test.questions
важно:
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами нужна страница для вывода теста
что приводит к следующим выводам:
- экшен `index` в классе `QuestionsController` лишний
- вызов коллбека для `index` не нужен
- список вопросов нужно выводить на странице теста
- путь `test_questions_path`, который ты используешь в экшенах, тоже лишний (нужно отменить его создание в `routes`)
- нужен контроллер для ресурса `:tests` (его написание было поэтапно продемонстрировано в скринкасте)

2022-10-21 09:50 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>      @question=@test.questions.new(question_params)
не забываем про пробельчики
`@question = @test.questions.new(question_params)`

2022-10-21 09:50 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to action: :show, id: @question.id
можно написать короче
`redirect_to @question`

2022-10-21 09:50 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    #@test= @question.test
что это?)

2022-10-21 09:50 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>       end
обычно ресурсы должны удаляться без проблем. Если это не так, то это проблема кода, а не юзера

2022-10-21 09:50 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @test=Test.order(params[:sort])
пробелы. Надо следить за чистотой кода. 
Используй rubocop для автоматизации процесса.
Еще есть инструменты, которые будут запускать линтер автоматически

2022-10-21 09:50 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @test.user_id=1
стоит привыкнуть работать с объектами, а не с их атрибутами.
И если нет такого юзера с ИД = 1?
```ruby
author = User.first
@test = author.authored_tests.build(test_params)
```

2022-10-21 09:50 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    #render action: :show, id: @test.id
такие комментарии не нужны в проекте. Надо удалять за собой

2022-10-21 09:50 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    "<p style='text-align: center'><a href='#{author}'>Информация об авторе: Кириченко Юлия. </a><a href='#{repo}'>проект Тест Гуру</a></p>".html_safe
есть удобный хелпер link_to для ссылок
https://apidock.com/rails/ActionView/Helpers/UrlHelper/link_to

2022-10-21 09:50 UTC, VidgarVii commented on app/helpers/tests_helper.rb
> +  def test_level(test)
м/у методом и константой нужен отступ

2022-10-21 09:50 UTC, VidgarVii commented on app/helpers/tests_helper.rb
> +  TEST_LEVELS={0=>"Легкий", 1=>"Средне-легкий", 3=>"Средний", 4=>"Средне-сложный", 5=>"Сложный", 6=>"Очень сложный"}.freeze
массив это тот же хеш у которого ключи в виде цифр
`TEST_LEVELS = %w[Легкий Средне-легкий Средний ....].freeze`
так смотрится на много лучше
и метод test_level переписывать не придётся

2022-10-21 09:50 UTC, VidgarVii commented on app/helpers/tests_helper.rb
> +  end
можно еще написать так.
`TEST_LEVELS.fetch(test.level, 'В процессе создания')`
выглядит более декларативно

2022-10-21 09:50 UTC, VidgarVii commented on app/views/layouts/application.html.erb
> +<footer>
чтобы layouts остался чистым футер лучше положить в партиал

2022-10-21 09:50 UTC, VidgarVii commented on app/views/questions/_form.html.erb
> +  <%if action_name == 'edit' %>
это лишняя проверка
_Для того чтобы метод form_with смог сформировать верный URL используйте вызов form_with model: [@parent, @child]_
просто пишешь `form_with model: [@test, @question]`
для эдит переменная `@test` будет пустая (не надо ее в контроллере искать, т.к. при использовании опции "шеллоу тру" в роутах для эдит `@test` не нужен)
соответсвенно в `@test` будет "нил" и рельсы построят правильный путь, потому что придет только `@question`
для нью придут оба объекта ("тест" и "квесшен") и рельсы также построят правильный путь

2022-10-21 09:50 UTC, VidgarVii commented on app/views/shared/_question.html.erb
> +<%n=1 %>
это зачем?

2022-10-21 09:50 UTC, VidgarVii commented on app/views/tests/index.html.erb
> +  <%=render @test%>
`<%= render @test %>`

2022-10-23 07:19 UTC, VidgarVii requested changes

2022-10-23 07:19 UTC, VidgarVii commented on app/views/questions/index.html.erb
> -<div class="rails-default-about-page">
тут можно весь файл удалить, а не только код

2022-10-23 07:19 UTC, VidgarVii commented on app/views/tests/new.html.erb
>  </div>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file

2022-10-23 07:19 UTC, VidgarVii commented on app/views/tests/show.html.erb
> +    <%= render 'shared/question', resource:[@test, @question] %>
для рессурса вопросов есть уже папка questions
Там по умолчанию и должен лежить паршал для показа вопроса
достаточно было сделать так
`<%= render @test.questions %>`

2022-10-25 05:50 UTC, VidgarVii requested changes

2022-10-25 05:50 UTC, VidgarVii commented on app/helpers/questions_helper.rb
>  end
https://github.com/Yuliya-Kirich/thinknetika_base/pull/12#discussion_r1001581076
Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2022-10-25 05:50 UTC, VidgarVii commented on app/helpers/questions_helper.rb
>    def question_header
как этот код попал в мастер? хелпер пишется только на этом задании

2022-10-25 05:50 UTC, VidgarVii commented on app/helpers/questions_helper.rb
>        end} "), class: "strong")
не стоит полагаться на глобальное состояние (инстанс-переменные) в хелпере
лучше передавать вопрос параметром, иначе потом не разберешь откуда эти данные тут взялись
так же легко забыть, что здесь используется эта инстанс-переменная, переименовать ее при рефакторинге и сломать код

2022-10-25 15:46 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    content_tag(:p,  "2021 - #{Time.now.strftime('%Y')}")
в рельсах рекомендуется использовать `Time.current` вместо `Time.now` (`Time.new`) и `Date.current` вместо `Date.today`
`.current` возвращает текущий момент времени с учетом настройки часового пояса в приложении

2022-10-25 15:46 UTC, VidgarVii commented on app/views/questions/show.html.erb
>    <form action = "/questions/<%=@question.id%>" method="get">
не уверен что тут нужна форма. Форму показываем только при обновлении или создании вопроса

2022-10-25 23:45 UTC, Yuliya-Kirich commented on app/views/questions/show.html.erb
>    <form action = "/questions/<%=@question.id%>" method="get">
https://github.com/Yuliya-Kirich/thinknetika_base/pull/12/commits/4146389e622405ab425418e3a30046dcacdf4ccf

2022-10-25 23:45 UTC, Yuliya-Kirich commented on app/helpers/application_helper.rb
> +    content_tag(:p,  "2021 - #{Time.now.strftime('%Y')}")
https://github.com/Yuliya-Kirich/thinknetika_base/pull/12/commits/4146389e622405ab425418e3a30046dcacdf4ccf

2022-10-25 23:46 UTC, Yuliya-Kirich commented on app/helpers/questions_helper.rb
>        end} "), class: "strong")
https://github.com/Yuliya-Kirich/thinknetika_base/pull/12/commits/9678029e57072aa54c722eb24a0609f609395f97

2022-10-26 06:15 UTC, VidgarVii requested changes

2022-10-26 06:15 UTC, VidgarVii commented on app/controllers/tests_controller.rb
>     if @test.destroyed?
если рессур не может рекурсивно удалиться, то это баг. Весь код выше и проверки тут лишние
@test.destroy должен работать не зависимо от наличии дочерних объектов
соответственно экшен должен выглядеть примерно так

```ruby
@test.destroy

redirect_to tests_path
```

2022-10-26 06:15 UTC, VidgarVii commented on app/views/tests/show.html.erb
> +    <%= render @test.questions.first %>
по ТЗ надо показать все вопросы теста

2022-10-26 06:15 UTC, VidgarVii commented on app/views/tests/show.html.erb
> +  <%= form_with model: @test, local: true do |form| %>
для обновления теста, есть страница edit
Так же есть отдельный паршал для формы.
Хотя такой подход возможен, но мне кажется страница перегружена

2022-10-26 06:15 UTC, VidgarVii commented on config/locales/models/rb.yml
> +        user_id: "Пользователь"
не исправлено

2022-10-26 06:15 UTC, VidgarVii commented on config/locales/ru.yml
>        title: Список клиентов
не исправлено

2022-10-28 23:17 UTC, Yuliya-Kirich commented
1. implemented all standard actions and views for resource question. 
2. added footer, which displays the current year, author's name, project name. 
3. added the helper for the title of the page for creating and editing a question.
4. added date helper in footer.

2022-10-29 00:53 UTC, merged