Application Logic
Yuliya-Kirich/thinknetika_base pull request #14
Opened 2023-02-02 00:58 UTC by Yuliya-Kirich

1. next question in TestPassage model assign with callback; 
2. message and the percentage of success is determined by the number of correct answers; 
3. displays the number of the current question and the total number of test questions.

2023-02-02 06:02 UTC, BubuntuClu requested changes

2023-02-02 06:02 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +      if @answer.update(answer_params)
отступы поехали

2023-02-02 06:02 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +      else
отступы поехали

2023-02-02 06:02 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +     redirect_to @answer.question
следи за отступами

2023-02-02 06:02 UTC, BubuntuClu commented on app/helpers/answers_helper.rb
> +  def answer_header(question, answer)
сюда только ответ надо передавать

2023-02-02 06:02 UTC, BubuntuClu commented on app/helpers/answers_helper.rb
> +    content_tag(:div, content_tag(:h1, "#{t action_name} ответ на вопрос: #{if question.blank?
делали ведь уже подобный метод. ориентироваться стоит на состояние объекта, а не на имя метода

2023-02-02 06:02 UTC, BubuntuClu commented on app/helpers/answers_helper.rb
> +module AnswersHelper
беда с оформлением кода в файле, ничего не понятно

2023-02-02 06:02 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +    rate = @test_passage.correct_questions*100/@test_passage.test.questions.count
это стоит вынести в метод модели

2023-02-02 06:02 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +    content_tag(:div, content_tag(:p, if rate >= 85
дважды проверяешь одну и туже проверку, не оптимально

2023-02-02 06:02 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +    color_sensor = (rate >= 85)
проверку надо вынести в метод модели `passage.success?`

2023-02-02 06:02 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +    color_sensor = (rate >= 85)
число 85 без конектста задачи не имеет никакого смысла. это магическое число. надо вынести в константу и дать понятное имя

2023-02-02 06:02 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    self.current_question = next_question
установку след вопроса по условиям задачи надо сделать через колбэк

2023-02-02 06:02 UTC, BubuntuClu commented on app/models/user.rb
>      Test.joins('JOIN users_sessions on users_sessions.test_id=tests.id').where('level=?', level).where('user_id = ?', self.id).pluck(:title)
это все можно отрефакторить до вида `tests.where(level: level)`

2023-02-02 06:02 UTC, BubuntuClu commented on app/models/users_session.rb
> +  # belongs_to :user
это надо вернуть

2023-02-02 06:02 UTC, BubuntuClu commented on app/views/answers/_answer.html.erb
> +<tr>
отформатируй файл. какое-то полотно получилось, следи за отступами и вложенностью тэгов

2023-02-02 06:02 UTC, BubuntuClu commented on app/views/answers/_form.html.erb
> +<%= form_with model: [@question, @answer], local: true do |form| %>
отступ

2023-02-02 06:02 UTC, BubuntuClu commented on app/views/answers/edit.html.erb
> +<% @answer.question.body %>
этот код можно поместить внутрь формы. у тебя всегда есть объект ответа и у него есть вопрос.

2023-02-02 06:02 UTC, BubuntuClu commented on app/views/test_passages/show.html.erb
> +    <% @test_passage.test.question_ids.each_with_index do |question, index| %>
это плохое решение. надо сделать метод в моделе, который по текущему вопросу будет искать индекс. `find_index` метод тебе поможет

2023-02-02 06:02 UTC, BubuntuClu commented on config/routes.rb
> +  member do
отступы

2023-02-02 06:02 UTC, BubuntuClu commented on config/routes.rb
> +  member do
отступы

2023-02-02 06:02 UTC, BubuntuClu commented on db/migrate/20221124235637_create_test_passages.rb
> +    add_foreign_key(:test_passages, :questions, column: :current_question_id)
это надо сделать через опцию `foreign_key: { to_table: :question }` у строки `current_question`
измени эту миграцию

2023-02-02 06:02 UTC, BubuntuClu commented on db/migrate/20221125002542_drop_table_users_sessions.rb
> +    def up
если есть метод `up`, то должен быть и метод `down`, чтобы при откатывании миграции не словить ошибку.
в данном случае, метод `down` можно оставить пустым

2023-02-12 16:49 UTC, BubuntuClu requested changes

2023-02-12 16:49 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
>      @categories = Category.group(:number)
а зачем тебе эти категории? ты же их никак не используешь в этом экшене

2023-02-12 16:49 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  before_action :set_user, only: %i[create start update show new]
разве ты используешь объект пользователя где-то кроме старта теста?

2023-02-12 16:49 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +    content_tag(:div, content_tag(:p, if test_passage.success?
в одном методе ты 3 раза вызываешь проверку успеха. неоптимально. представь что проверка успеха это тяжелая операция и ты вызываешь ее 3 раза. надо написать код так, чтобы проверка происходила только один раз

2023-02-12 16:49 UTC, BubuntuClu commented on app/helpers/answers_helper.rb
> +    content_tag(:div, content_tag(:h1, "#{t action_name} ответ на вопрос: #{answer.question.body}"),
отойди от `action_name`. ориентируйся на состояние объекта

2023-02-12 16:49 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    number_for_question.index(number_for_question.find { |l| l == current_question }) + 1
что вернет код `test.questions.index(current_question)`?
твой код выглядит громоздко и сложно

2023-02-12 16:49 UTC, BubuntuClu commented on app/views/answers/_answer.html.erb
> +<tr>
это надо поправить

2023-02-12 16:49 UTC, BubuntuClu commented on app/views/answers/_form.html.erb
> +<%= form_with model: [@question, @answer], local: true do |form| %>
и это

2023-02-13 06:40 UTC, Yuliya-Kirich commented on app/controllers/tests_controller.rb
>      @categories = Category.group(:number)
Использую в form на который смотрит этот экшн. 
Если убрать, то получу ошибку в строке:
Showing /home/yk/Documents/TN/thinknetika_base/app/views/tests/_form.html.erb where line #18 raised:
undefined method `map' for nil:NilClass
<%=form.collection_select :category_id, @categories, :number, :type_of_category, {selected:  @test.category_id || Category.all.map(& :id), include_hidden: false}, prompt: true, uniq:true, class:"collection_select"%>
        </div>
      </div>
  <br><br><br>

2023-02-13 06:46 UTC, Yuliya-Kirich commented on app/controllers/tests_controller.rb
> +  before_action :set_user, only: %i[create start update show new]
В create.
 Если убрать, ошибка - NoMethodError in TestsController#create
undefined method `authored_tests' for nil:NilClass
Extracted source (around line #20):
@test = @user.authored_tests.build(test_params)

Лишние уберу

2023-02-13 16:36 UTC, BubuntuClu commented on app/helpers/answers_helper.rb
> +      ANSWERS_FSM[1]
завязывать логику на порядковом номере массива плохая идея. кто-то добавит что-то, и уже будет не правильно работать код. верни тут просто нужный текст. зачем тебе массив?

2023-02-14 03:47 UTC, Yuliya-Kirich commented
1. next question in TestPassage model assign with callback;
2. message and the percentage of success is determined by the number of correct answers;
3. displays the number of the current question and the total number of test questions.

2023-02-14 03:48 UTC, merged