authentication & user sessions
Yuliya-Kirich/thinknetika_base pull request #15
Opened 2023-02-17 00:11 UTC by Yuliya-Kirich

1. Add a user ID to the session after registering it.
2. Create a helper for flash messages.
3. Implement user logout.
4. Create a navigation with the name of the project and links for user registration/login/logout. If the user is logged in, display the message Welcome, <user name> Guru. The name of the project should be a link and lead to the main page of the application.
5. Allow actions on other resources only for the user who is login.
6. Using the cookie mechanism, redirect the user after login to the page where he originally wanted to go.
7. Check the format and uniqueness of the user's email attribute.
8. Use the current user object when starting the test.

2023-03-25 18:45 UTC, BubuntuClu requested changes

2023-03-25 18:45 UTC, BubuntuClu commented on config/routes.rb
> +  get 'users/new'
дублирование пути на 4ой строке7 надо удалить эту строку

2023-03-25 18:45 UTC, BubuntuClu commented on db/schema.rb
> +    t.string "email"
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный индекс надо

2023-03-25 18:45 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>  class QuestionsController < ApplicationController
почему в этом контроллере не надо проверять авторизацию пользователя?
если забыла, то может просто указать этот метод колбэком в родитесльком контроллере чтобы в каждом дочернем не прописывать этот колбэк?

2023-03-25 18:45 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :redirect_url_remember
это тоже кажется стоит разместить в родительском контроллере, а не прописывать в каждом контроллере

2023-03-25 18:45 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:redirect_url] || root_path
старайся редирект делать последним методом в выполняемом коде

2023-03-25 18:45 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +      redirect_to root_url unless current_user.id == @answer.question.test.user_id
`unless` воспринимается сложнее чем `if`. старайся использовать `if` всегда когад это возможно

2023-03-25 18:45 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    if logged_in?
по идеи этой проверки тут не должно быть, это проверяет `authenticate_user`

2023-03-25 18:45 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:email] = current_user&.email
для чего ты сохраняешь почту? как ты потом это используешь?

2023-03-25 18:45 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  def redirect_url_remember
не делай это отдельным методом. сохраняй путь куда сделать редиекрт в коде  `authenticate_user!` если пользователь не аторзован. не плоди лишние колбэки, с увеличением колбэков ты условжняешь лоигку приложения

2023-03-25 18:45 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = Test.where(user_id: @current_user.id).order(params[:sort])
нужно обращаться к методу `current_user`, а не к переменной. надо заменить использование инстанс переменной на вызов метода везде где это сделано

2023-03-25 18:45 UTC, BubuntuClu commented on app/models/user.rb
> +  validates_format_of :email, :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
`with: ...`

2023-03-25 18:45 UTC, BubuntuClu commented on app/models/user.rb
> +  validates_format_of :email, :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
проверку формата сделай опцией к `validates :email, uniqueness: true`
то как ты сейчас сделала, это старый синатксис валидации

2023-03-26 17:33 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    redirect_url_remember
запоминать стоит только если пользователь не авторизован. если авторизован то его пустит туда, куда он хотел и нет смысла запоминать

2023-03-26 17:33 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = Test.where(user_id: current_user.id).order(params[:sort])
у тебя есть ассоциация на авторские тесты. используй ее, вместо ручного написания запроса

2023-03-26 17:33 UTC, BubuntuClu commented on app/models/user.rb
> +  validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
эту строку надо заменить опцией к строке ниже. ты используешь старый синтаксис

2023-03-29 22:06 UTC, Yuliya-Kirich commented
1. Add a user ID to the session after registering it.
2. Create a helper for flash messages.
3. Implement user logout.
4. Create a navigation with the name of the project and links for user registration/login/logout. If the user is logged in, display the message Welcome, Guru. The name of the project should be a link and lead to the main page of the application.
5. Allow actions on other resources only for the user who is login.
6. Using the cookie mechanism, redirect the user after login to the page where he originally wanted to go.
7. Check the format and uniqueness of the user's email attribute.
8. Use the current user object when starting the test.

2023-03-29 22:06 UTC, merged