Using active records query interface
Yuliya-Kirich/thinknetika_base pull request #5
Opened 2021-04-25 20:47 UTC by Yuliya-Kirich

- Набор начальных данных для всех существующих моделей в файле db/seeds.rb

- Инстанс-метод в модели User, который принимает в качестве аргумента значение уровня сложности и возвращает список всех Тестов, которые проходит или когда-либо проходил Пользователь на этом уровне сложности

- Метод класса в модели Test, который возвращает отсортированный по убыванию массив названий всех Тестов у которых Категория называется определённым образом (название категории передается в метод в качестве аргумента).

2021-04-26 07:11 UTC, BubuntuClu requested changes

2021-04-26 07:11 UTC, BubuntuClu commented on app/models/user.rb
> +  def initialize(current_user)
это не надо делать для получения текущего пользователя

2021-04-26 07:11 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.joins('JOIN users_sessions on users_sessions.test_id=tests.id').where('level=?', level).where('user_id==?', @current_user)
`'user_id==?'` один пробел надо оставить

ты пишешь инстанс-метод, значит этот метод будет вызываться от объекта класса. получается что внутри этого метода через `self` ты можешь получить текущего пользователя

2021-04-26 07:11 UTC, BubuntuClu commented on app/models/user.rb
> +  def initialize(current_user)
можешь написать код вызова своего метода ниже? интересно посмотреть как ты собиралась его использовать

2021-04-26 19:19 UTC, BubuntuClu approved these changes

2021-04-26 19:19 UTC, BubuntuClu commented on db/migrate/20210222214056_rename_column_to_categories.rb
> +    rename_column(:categories , :type, :type_of_category)
а зачем это делать? имя параметра ника не связано с именем поля в БД

2021-04-26 19:19 UTC, BubuntuClu commented on app/models/test.rb
> +  def self.search_to_categories_title(type_of_category)
почему типа категории? название передаем

2021-04-26 19:19 UTC, BubuntuClu commented on app/models/user.rb
> +    (Test.joins('JOIN users_sessions on users_sessions.test_id=tests.id').where('level=?', level).all.where('user_id = ?', self.id)).pluck(:title)
скобки лишние как и `all`

2021-04-29 14:21 UTC, Yuliya-Kirich commented
Набор начальных данных для всех существующих моделей в файле db/seeds.rb

Инстанс-метод в модели User, который принимает в качестве аргумента значение уровня сложности и возвращает список всех Тестов, которые проходит или когда-либо проходил Пользователь на этом уровне сложности

Метод класса в модели Test, который возвращает отсортированный по убыванию массив названий всех Тестов у которых Категория называется определённым образом (название категории передается в метод в качестве аргумента).

2021-04-29 14:22 UTC, merged